suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(tgutil))
suppressPackageStartupMessages(library(tgstat))
suppressPackageStartupMessages(library(glue))
suppressPackageStartupMessages(library(misha))
suppressPackageStartupMessages(library(cli))
# suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(misha.ext))
suppressPackageStartupMessages(library(bigsnpr))
suppressPackageStartupMessages(library(bigreadr))
suppressPackageStartupMessages(library(labNorm))
suppressPackageStartupMessages(library(mldpEHR))

doMC::registerDoMC(40)
gset_genome("hg19")
options(gmax.data.size = 1e9)

CENSOR_DATE <- data.table::fread(here::here('data/censor_date.csv'))
DEATH_CENSOR_DATE <- lubridate::dmy(CENSOR_DATE %>% filter(type == "death") %>% pull(date))
DISEASE_CENSOR_DATE <- lubridate::dmy(CENSOR_DATE %>% filter(type == "dx") %>% pull(date))